#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_GOOGLE_include_directive : enable

#include "utils.glsl"

layout (local_size_x = 16, local_size_y = 16) in;
layout (rgba8, binding = 0) uniform writeonly image2D outputImage;

layout (binding=1) uniform samplerBuffer vertexBuffer;

layout(push_constant) uniform PushConstants {
	float time;
} pushConstants;

const int SUBPIXEL_BITS = 4;
const bool BACKFACE_CULL = true;

ivec3 round_to_subpixel(vec3 v)
{
	return ivec3(floor(v * float(1 << SUBPIXEL_BITS) + 0.5));
}

struct primitive {
	vec2 bmin, bmax; // bounding box

	ivec3 e[3]; // edge functions

	// z, w, and barycentric interpolants
	vec3 fz, fw, fi, fj;
};

void calc_bbox_trivial(vec4 verts[3], out vec2 bmin, out vec2 bmax)
{
	bmin = imageSize(outputImage);
	bmax = vec2(0);
	for (int i = 0; i < 3; ++i) {
		// assert(verts[i].w > 0);
		bmin = min(bmin, verts[i].xy);
		bmax = max(bmax, verts[i].xy);
	}
}

void calc_bbox(vec4 verts[3], out vec2 bmin, out vec2 bmax)
{
	ivec2 iResolution = imageSize(outputImage);
	bmin = iResolution;
	bmax = vec2(0);
	bvec2 xpos = bvec2(false), xneg = bvec2(false);
	for (int i = 0; i < 3; ++i) {
		if (verts[i].w > 0) {
			bmin = min(bmin, verts[i].xy);
			bmax = max(bmax, verts[i].xy);
		} else {
			int j = (i + 1) % 3;
			if (verts[j].w > 0) {
				bvec2 s = greaterThan(verts[j].xy, verts[i].xy);
				xpos = bvec2(xpos.x || s.x, xpos.y || s.y);
				xneg = bvec2(xneg.x || !s.x, xneg.y || !s.y);
			}

			int k = (i + 2) % 3;
			if (verts[k].w > 0) {
				bvec2 s = greaterThan(verts[k].xy, verts[i].xy);
				xpos = bvec2(xpos.x || s.x, xpos.y || s.y);
				xneg = bvec2(xneg.x || !s.x, xneg.y || !s.y);
			}
		}
	}
	for (int i = 0; i < 2; ++i) {
		if (xpos[i])
			bmax[i] = iResolution[i];
		if (xneg[i])
			bmin[i] = 0;
	}
}

mat3 calc_adjoint(vec4 verts[3], vec3 tmp)
{
	mat3 adj;
	for (int i = 0; i < 3; ++i) {
		int j = (i + 1) % 3;
		int k = (i + 2) % 3;
		adj[i].x = verts[j].y - verts[k].y;
		adj[i].y = verts[k].x - verts[j].x;
		adj[i].z = tmp[i];
	}
	return adj;
}

ivec3 adjust_fill_rule(ivec3 e)
{
	if (e.x < 0)
		e.z++; // top-rule
	else if (e.x == 0) {
		if (e.y < 0)
			e.z++; // left-rule
	}
	return e;
}

void setup_interpolants(vec4 verts[3], mat3 adj, float det, inout primitive result)
{
	result.fw = adj[0] * verts[0].w;
	result.fi = adj[1] * verts[1].w;
	result.fj = adj[2] * verts[2].w;
	result.fw += result.fi + result.fj;
	result.fz = (adj[0] * verts[0].z +
				 adj[1] * verts[1].z +
				 adj[2] * verts[2].z) / det;
}

vec3 reduce_edge_range(vec3 ef)
{
	// reduce edge-function range to avoid 32-bit overflow later.
	// we're still adding subpixel bits later, so this isn't as low as
	// it sounds.

	float mag = max(abs(ef.x), max(abs(ef.y), abs(ef.z)));
	const float limit_log2 = 23;
	if (mag >= exp2(limit_log2))
		ef *= exp2(-floor(log2(mag)) + limit_log2);
	return ef;
}

bool setup_tri_trivial(vec4 verts[3], out primitive result)
{
	// calculate enough of the adjoint to calculate the determinant
	vec3 tmp = cross(vec3(verts[0].x, verts[1].x, verts[2].x),
					 vec3(verts[0].y, verts[1].y, verts[2].y));

	// backface culling
	float det = tmp.x + tmp.y + tmp.z;
	if (BACKFACE_CULL && det <= 0)
		return false;
	calc_bbox_trivial(verts, result.bmin, result.bmax);

	mat3 adj = calc_adjoint(verts, tmp);

	// edge-functions (snapped to subpixels)
	for (int i = 0; i < 3; ++i) {
		vec3 ef = reduce_edge_range(adj[i]);
		ivec3 e = round_to_subpixel(ef);
		result.e[i] = adjust_fill_rule(e);
	}

	setup_interpolants(verts, adj, det, result);
	return true;
}

bool setup_tri(vec4 verts[3], out primitive result)
{
	if (verts[0].w > 0 && verts[1].w > 0 && verts[2].w > 0)
		return setup_tri_trivial(verts, result);

	// calculate enough of the adjoint to calculate the determinant
	vec3 tmp = cross(vec3(verts[0].x, verts[1].x, verts[2].x),
					 vec3(verts[0].y, verts[1].y, verts[2].y));

	// backface culling
	float det = tmp.x + tmp.y + tmp.z;
	if (BACKFACE_CULL && det * verts[0].w * verts[1].w * verts[2].w <= 0)
		return false;

	calc_bbox(verts, result.bmin, result.bmax);

	mat3 adj = calc_adjoint(verts, tmp);

	bool inv_edge[3];
	inv_edge[0] = verts[1].w * verts[2].w <= 0;
	inv_edge[1] = verts[2].w * verts[0].w <= 0;
	inv_edge[2] = verts[0].w * verts[1].w <= 0;

	// edge-functions (snapped to subpixels)
	for (int i = 0; i < 3; ++i) {
		vec3 ef = reduce_edge_range(adj[i]);
		ivec3 e = round_to_subpixel(ef);
		if (inv_edge[i])
			e = -e;
		result.e[i] = adjust_fill_rule(e);
	}

	setup_interpolants(verts, adj, det, result);
	return true;
}

int eval_edge(ivec3 e, ivec2 pos)
{
	return e.x * pos.x + e.y * pos.y + e.z;
}

void debugFrag(uvec2 fragCoord, vec4 color)
{
#if 1
	imageStore(outputImage, ivec2(fragCoord), color);
#endif
}

vec4 attrs[3] = vec4[3](
	vec4( 1,  0, 0, 0),
	vec4( 0,  1, 0, 0),
	vec4( 0,  0, 1, 0)
);

vec4 perVertex(vec4 vert) {
	// viewport map
	ivec2 iResolution = imageSize(outputImage);

	float w_rcp = 1 / vert.w;
	// clamp 1 / w to avoid problems at infinity
	const float w_rcp_range = exp2(20);
	w_rcp = clamp(w_rcp, -w_rcp_range, w_rcp_range);

	vec3 tmp = vert.xyz * w_rcp;
	return vec4(iResolution.xy * 0.5 + tmp.xy * iResolution.xy * 0.5,
	            tmp.z, w_rcp);
}

void perFragment(in uvec2 fragCoord, in primitive prim)
{
	ivec2 pos = ivec2(fragCoord.xy);
	int d0 = eval_edge(prim.e[0], pos);
	int d1 = eval_edge(prim.e[1], pos);
	int d2 = eval_edge(prim.e[2], pos);

	if (min(min(d0, d1), d2) > 0) {
		// depth-clip
		float z = dot(prim.fz, vec3(pos, 1));
#if 0
		if (z < 0 || z > 1) {
			debugFrag(fragCoord, vec4(0, 0, 0.5, 1));
			return;
		}
#else
		z = clamp(z, 0, 1);
#endif

		float i = dot(prim.fi, vec3(pos, 1));
		float j = dot(prim.fj, vec3(pos, 1));
		float w = 1 / dot(prim.fw, vec3(pos, 1));

		i *= w;
		j *= w;
		float k = 1 - i - j;

		// interpolate a single vec4 varying
		vec4 var = attrs[0] * k + attrs[1] * i + attrs[2] * j;
		vec4 fragColor = var;
#if 0
		vec4 tmp = vec4(textureLod(iChannel0, var.xy, 0).xyz, 1);
		tmp.xyz = mix(tmp.xyz, vec3(0.5), 1 / (1 + z));
		fragColor *= tmp;
#endif
		imageStore(outputImage, ivec2(fragCoord), fragColor);
	}
}

shared vec4 verts[3];

void main()
{
	uvec2 fragCoord = gl_GlobalInvocationID.xy;
	imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), vec4(0));
	float iTime = pushConstants.time;
	ivec2 iResolution = imageSize(outputImage);

	// *** per vertex
	if (gl_LocalInvocationID.x < 3) {
		uint i = gl_LocalInvocationID.x;
		vec4 vert = texelFetch(vertexBuffer, int(i));
		verts[i] = perVertex(vert);
	}

	groupMemoryBarrier();
	barrier();

	// *** per primitive

	primitive prim;
	if (!setup_tri(verts, prim)) {
		debugFrag(fragCoord, vec4(0.5, 0, 0, 1));
		return;
	}


	/* this really belongs elsewhere, but it's cleaner to color here */
	if (any(lessThan(fragCoord.xy, floor(prim.bmin.xy))) ||
		any(greaterThan(fragCoord.xy, ceil(prim.bmax.xy)))) {
		debugFrag(fragCoord, vec4(0, 0.5, 0.5, 1));
		return;
	}

	// *** per tile
	debugFrag(fragCoord, vec4(0.5, 0, 0, 1));

	/* just proof-of-concept: conservative
	 * block-rasterizing, for hierarchial
	 * rasterization (and could be repurposed
	 * for normal conservative rasterization)
	 */
	ivec3 de, ne;
	for (int i = 0; i < 3; ++i) {
		de[i] = max(prim.e[i].x, 0) + max(prim.e[i].y, 0);
		ne[i] = prim.e[i].x + prim.e[i].y - de[i];
	}

	vec4 debugColor = vec4(1);
	for (int i = 6; i > 0; i--) {
		ivec2 hpos = ivec2(fragCoord.xy) & ~((1 << i) - 1);
		ivec3 d;
		for (int j = 0; j < 3; ++j)
			d[j] = eval_edge(prim.e[j], hpos);

		bool fully_outside = any(lessThan(d + (de << i), ivec3(0)));
		if (fully_outside) {
			debugColor[i % 3] *= 0.875 / float(1 + i / 3);
			debugFrag(fragCoord, debugColor);
			return;
		}

		bool fully_inside = all(greaterThan(d + (ne << i), ivec3(0)));
		if (fully_inside) {
			debugColor[i % 3] *= 0.875 / float(1 + i / 3);
			break;
		}
	}
	debugFrag(fragCoord, debugColor);

	perFragment(fragCoord, prim);
}
