#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_GOOGLE_include_directive : enable

#include "utils.glsl"

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0) uniform writeonly image2D outputImage;
layout (binding = 1) uniform sampler2D samplerColor;
layout (binding = 2) uniform sampler2D samplerBloom;
layout (binding = 3) uniform sampler2DArray overlaySampler;
layout (binding = 4) uniform sampler3D colorLut1;
layout (binding = 5) uniform sampler3D colorLut2;

layout(push_constant) uniform PushConstants {
	int overlayIndex;
	int frameSeed;
	float bloomAmount;
	float overlayAlpha;
	float fade;
	float flash;
	float kaleidoCount;
	float gradeBlend;
	float gradeAmount;
} pushConstants;

vec2 kaleidoscope(vec2 pos, float count)
{
	float th = atan(pos.y, pos.x);
	float r = length(pos);

	float f = 3.14159265 / count;
	th += 3.14159265 * 0.5;
	th = abs(mod(th, 2 * f) - f) + f;
	th -= 3.14159265 * 0.5;

	return vec2(cos(th), sin(th)) * r;
}

void main()
{
	vec2 pos = (gl_GlobalInvocationID.xy + 0.5) / imageSize(outputImage);

	vec2 kaleidoPos = pos;
	if (pushConstants.kaleidoCount > 0) {
		vec2 size = imageSize(outputImage);
		kaleidoPos = 0.5 + kaleidoscope(vec2(gl_GlobalInvocationID.xy) + 0.5 - size * 0.5, pushConstants.kaleidoCount) / size;
	}

	vec3 color = texture(samplerColor, kaleidoPos).xyz;
	color += texture(samplerBloom, kaleidoPos).xyz * pushConstants.bloomAmount;

	// vignette
	color *= 1.0 - distance(pos, vec2(0.5));

	color = color * pushConstants.fade + pushConstants.flash;

	vec3 gradeColor1 = toLinear(textureLod(colorLut1, color, 0).rgb);
	vec3 gradeColor2 = toLinear(textureLod(colorLut2, color, 0).rgb);
	vec3 gradeColor = mix(gradeColor1, gradeColor2, pushConstants.gradeBlend);
	color = mix(color, gradeColor, pushConstants.gradeAmount);

	uint pixelSeed = rand(137 + gl_GlobalInvocationID.x) | (rand(8 + gl_GlobalInvocationID.y) << 4);
	color += randf(pixelSeed ^ pushConstants.frameSeed) * (2.0 / 255);

	vec4 overlay = textureLod(overlaySampler, vec3(pos.xy, pushConstants.overlayIndex), 0);
	color = color * (1 - overlay.a * pushConstants.overlayAlpha) + overlay.rgb * pushConstants.overlayAlpha;

	imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), vec4(color, 1));
}
